// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMO0PsGSZnlvy0vluhflO73i6ERGaTYyU',
    appId: '1:164501164196:web:67ee91a658dd4d58d59631',
    messagingSenderId: '164501164196',
    projectId: 'mest-kitchen',
    authDomain: 'mest-kitchen.firebaseapp.com',
    storageBucket: 'mest-kitchen.appspot.com',
    measurementId: 'G-1HBN3W2X9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_Rvz-If_ZVFpGY8m9smp4hQbhAYeq-o',
    appId: '1:164501164196:android:1793a6ceb01e15c6d59631',
    messagingSenderId: '164501164196',
    projectId: 'mest-kitchen',
    storageBucket: 'mest-kitchen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm97IDbi576qeJozxUXGfv-LHUQ9oxthc',
    appId: '1:164501164196:ios:a7fab527ef8f363ed59631',
    messagingSenderId: '164501164196',
    projectId: 'mest-kitchen',
    storageBucket: 'mest-kitchen.appspot.com',
    iosClientId: '164501164196-tkmb8kajulpubisqr7uleedpgsvip419.apps.googleusercontent.com',
    iosBundleId: 'com.example.mestKitchenApp',
  );
}
